import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { ThemeProvider } from "@/components/Providers/ThemeProvider";
import { ConditionalLayout } from "@/components/AppLayout/ConditionalLayout";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Dashboard Design",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider
            style={{
              "--sidebar-width": "calc(var(--spacing) * 60)",
              "--header-height": "calc(var(--spacing) * 12)",
            }}
          >
            <ConditionalLayout>{children}</ConditionalLayout>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
